# Generated by Django 5.2 on 2025-04-03 21:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=250)),
                ('type', models.CharField(choices=[('waterfall', 'Waterfall'), ('viewpoint', 'Viewpoint'), ('historical', 'Historical Site'), ('visitor_center', 'Visitor Center'), ('cave', 'Cave'), ('lake', 'Lake'), ('trailhead', 'Trailhead'), ('other', 'Other')], max_length=55)),
            ],
        ),
        migrations.AddField(
            model_name='park',
            name='main_attractions',
            field=models.ManyToManyField(to='my_app.attraction'),
        ),
        migrations.CreateModel(
            name='Trail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('length_miles', models.FloatField()),
                ('difficulty', models.CharField(max_length=50)),
                ('park', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trails', to='my_app.park')),
            ],
        ),
    ]
