# Generated by Django 5.2 on 2025-04-03 22:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_attraction_park_main_attractions_trail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='park',
            name='main_attractions',
        ),
        migrations.RemoveField(
            model_name='trail',
            name='park',
        ),
        migrations.AddField(
            model_name='attraction',
            name='park',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attractions', to='my_app.park'),
        ),
        migrations.AddField(
            model_name='park',
            name='trails',
            field=models.ManyToManyField(to='my_app.trail'),
        ),
    ]
